name: CI

on:
  create:
    tags:
      - "*"

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "true"

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Install platformIO libraries
        run: pio lib install
      - name: Run PlatformIO
        run: platformio run

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-east-1"

      - name: Upload firmware to S3
        run: |
          aws s3 cp .pio/build/luftsentry/firmware.bin s3://${{ secrets.AWS_BUCKET }}/binaries/firmware.bin

      - name: Extract tag name
        id: extract_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Perform cURL request
        run: |
          TAG_NAME=${{ env.TAG_NAME }}
          curl --location --request PUT 'https://api.luftsentry.com/v1/ota' \
          --header 'Content-Type: application/json' \
          --data "{
            \"key\": \"7L\$6WnuvQ0eM\",
            \"device\": \"esp32\",
            \"url\": \"url\",
            \"version\": \"${TAG_NAME}\"
          }"
